### PR TITLE
Update serial_posix.go

### LINKED ISSUE #40: serial_posix broken
Using go 1.17:

```
❯ go get -u
go: downloading github.com/grid-x/serial v0.0.0-20211028062334-07e419efa8cd
go: downloading golang.org/x/net v0.0.0-20211029224645-99673261e6eb
go: downloading github.com/russross/blackfriday v1.6.0
go: downloading golang.org/x/sys v0.0.0-20211029165221-6e7872819dc8
go: downloading github.com/kr/pretty v0.2.0
go: downloading gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15
# github.com/grid-x/serial
../../go/pkg/mod/github.com/grid-x/serial@v0.0.0-20211028062334-07e419efa8cd/serial_posix.go:116:9: undefined: io
```

https://github.com/grid-x/serial/blob/master/serial_posix.go is missing the `io` import. Should use `goimports` when editing ;)

### PR DESCRIPTION
**Pull request by andig**
Fix https://github.com/grid-x/modbus/issues/40. Compile has been broken ever since https://github.com/grid-x/serial/commit/a65c1172de0be9e9a3f7d1677864f466026a00ba.

### CODE REVIEW

**Comment by andig** [comment]
Ping @gq0 building is broken- could we please get this merged?

**Review by frzifus — APPROVED** [review]

**Review by gq0 — APPROVED** [review]

**Comment by gq0** [comment]
Uff, my bad in a previous PR 🙈

**Comment by andig** [comment]
Would be nice to catch this in ci.

**Comment by frzifus** [comment]
There is no ci. Just a deprecated travis file[0]. :dancers: 

0: https://github.com/grid-x/serial/blob/master/.travis.yml
